apiVersion: v1
kind: Service
metadata:
  labels:
    name: dubbo-provider-svc
  name: dubbo-provider-svc
  namespace: kube-ym-ad
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9000
    nodePort: 9000
    name: dubbo-provider-svc-9000
  selector:
    app: dubbo-provider-app